apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: my-pod
  labels:
    app: my-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.19.2
      ports:
        - containerPort: 80
