name: Container Lifecycle
checks:
  - id: stop_container
    name: Stop Container
    command: docker
    args: inspect --format="{{.State.Status}}" my-nginx
    operator: CONTAINS
    expectation: exited
    successText: The container with the name my-nginx has exited.
    failureText: The container with the name my-nginx is not in the state exited.
