name: Container Lifecycle
checks:
  - id: check_directory
    name: Check Directory
    command: pwd
    args: 
    operator: EQUALS
    expectation: ./training/fake
    successText: You are in the ./training/fake directory
    failureText: You should be in the ./training/fake directory
  - id: check_contents_of_directory
    name: Check contents of Directory
    command: ls
    args: 
    operator: EQUALS
    expectation: 
    successText: No files are in the ./training/fake directory
    failureText: No files should be in the ./training/fake directory
