name: Kubernetes Fundametals
topics:
  - id: intro
    name: Intro
    slidesUrl: https://docs.google.com/presentation/d/1gxNSsHacD42O-zPciMwZYc9PFRjrjMUMUmr4y13WRyM
  - id: k8s-architecture
    name: Kubernetes Architecture
    # slidesUrl: https://docs.google.com/presentation/d/1a1ie8oazKuVjOpGjxDeA-1XFrEEuKU9ZwS5Gerlbv2g
    videoUrl: https://www.youtube.com/embed/sbjsaI6QAHM
    tasks:
      - directory: hello-k8s
  - id: services
    name: Services
    # slidesUrl: https://docs.google.com/presentation/d/1UZia1JK_W22GV6hVd5uYuXGfytJJTbCsyHnsaVMj-kw
    videoUrl: https://www.youtube.com/embed/N_3L60sjG6k
    tasks:
      - directory: services_clusterip
      - directory: services_nodeport

