name: Kubernetes Fundametals
topics:
  - id: topic01
    name: First topic
    slideUrl: https://somewhere.org/1
    tasks:
      - name: hello-k8s
        id: hello-k8s
      - name: pods
        id: pods
  - id: topic02
    name: Some other topic
    slideUrl: https://somewhere.org/2
    tasks:
      - name: hello-something
        id: hello-something
      - name: pods-again
        id: pods-again
