name: Hello Kubernetes
checks:
  - id: pod_running
    name: Pod my-pod is running
    command: kubectl
    args: -n default get pod my-pod -o jsonpath='{.status.containerStatuses[0].ready}'
    operator: EQUALS
    expectation: "true"
    successText: Pod my-pod is in state running
    failureText: Pod my-pod is not in state running
  - id: service_exists
    name: Service my-service exists
    command: kubectl
    args: -n default get svc my-service -o jsonpath='{.metadata.name}'
    operator: EQUALS
    expectation: my-service
    successText: Service my-service exists
    failureText: Service my-service does not exist
