apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: my-service
spec:
  selector:
    app: my-deployment
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
