name: Container Interaction
question:
  type: SINGLE_CHOICE
  options:
    - "1"
    - "5"
    - "3"
    - "4"
    - "2"
  rightAnswer: 2
  successText: Exactly, 2 containers are running currently.
  failureText: No, that is not the number of running containers.
