name: ClusterIP Service
checks:
  - id: pod_running
    name: Pod my-pod is running
    command: kubectl
    args: kubectl -n default get deployment my-deployment -o jsonpath='{.status.readyReplicas}'
    operator: EQUAL
    expectation: 1
    hint: The Deployment has to have at least one running pod
  - id: service_exists
    name: Service my-service exists
    command: kubectl
    args: -n default get svc my-service -o jsonpath='{.metadata.name}' 
    operator: EQUAL
    expectation: my-service
    hint: Service my-service does not exist
  - id: service_type_is_clusterip
    name: Service my-service is of type ClusterIp
    command: kubectl
    args: -n default get svc my-service -o jsonpath='{.spec.type}'
    operator: EQUAL
    expectation: ClusterIP
    hint: Ensure that the service is of type ClusterIP
