name: ClusterIP Service
checks:
  - command: kubectl
    args: -n default get deployments -o jsonpath='{.items[?(@.metadata.name=="my-nginx")].status.readyReplicas}'
    operator: EQUALS
    expectation: something
    hint: FAKE