name: My first Pod
checks:
  - id: fake
    name: FAKE
    command: kubectl
    args: -n default get deployments -o jsonpath='{.items[?(@.metadata.name=="my-nginx")].status.readyReplicas}'
    operator: EQUAL
    expectation: something
    hint: FAKE